spring:
  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/card_system?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root  #
    password: 1234  # ??MySQL??
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Thymeleaf??
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false  # ????????

  # ??????
  servlet:
    multipart:
      max-file-size: 10MB  # ??????10MB
      max-request-size: 100MB  # ??????100MB

# MyBatis??
mybatis:
  mapper-locations: classpath:mybatis/*.xml  # ??????
  type-aliases-package: com.card.po  # ??????
  configuration:
    map-underscore-to-camel-case: true  # ??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL??

# ?????
server:
  port: 8080
  servlet:
    context-path: /card  # ???????http://localhost:8080/card

# ????????????
upload:
  path: src/main/resources/static/upload/  # ??????
  access-path: /upload/  # ??????